[project]
name = "o-platy60-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.117.1",
    "pydantic>=2.11.9",
    "requests>=2.32.5",
    "sqlmodel>=0.0.25",
    "supabase>=2.20.0",
]
